source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DWChromecast_Example', :exclusive => true do
  pod "DWChromecast", :path => "../"
end

target 'DWChromecast_Tests', :exclusive => true do
  pod "DWChromecast", :path => "../"

  pod 'FBSnapshotTestCase'
end
