source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DWChromecast_Example', :exclusive => true do
  pod "DWChromecast", :path => "../"
end

target 'DWChromecast_Tests', :exclusive => true do
  pod "DWChromecast", :path => "../"
end

pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    def installer.verify_no_static_framework_transitive_dependencies; end
end